name: Publish package to NPM

on:
  push:
    branches:
    - master # Push events on master branch

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install node v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: npm install
        run: npm install
      # - name: build
      #   run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
